server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ekumen-bank-clients
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: false
  r2dbc:
    url: "r2dbc:postgresql://host.docker.internal:5433/ekumen-bank"
    username: ekumen-bank
    password: ekumen-bank
    show-sql: true
logging:
  level:
    ec:
      dev:
        samagua:
          ekumen_bank_clients: DEBUG


ekumen-bank-accounts:
  url: http://ekumen-cloud-gateway:8762/ekumen-bank-accounts/api