server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ekumen-bank-clients
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: false
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/ekumen-bank"
    username: postgres
    password: password
    show-sql: true
logging:
  level:
    ec:
      dev:
        samagua:
          ekumen_bank_clients: DEBUG


ekumen-bank-accounts:
  url: http://localhost:8762/ekumen-bank-accounts/api